### ISSUE TITLE
El logo en la pantalla principal tiene un fondo sucio, debe tener un fondo transparente

### ISSUE THREAD

**Issue by ecamacho** [springhispano/website#3]
Creo que se puede sustituir por un _PNG_ o _GIF_ con un fondo transparente, actualmente es un JPG https://s3-us-west-2.amazonaws.com/slack-files2/avatars/2015-07-18/7876620567_01501074b2903b39ace5_68.jpg

![screen shot 2015-09-04 at 6 09 30 pm](https://cloud.githubusercontent.com/assets/22887/9696376/6b0685f4-5334-11e5-8c70-6415b666401a.png)

**Comment by domix** [comment]
ohh si, me vi muy flojo y tomé el del Slack
