### ISSUE TITLE
Ghost

### ISSUE THREAD

**Issue by ripper2hl** [springhispano/website#5]
Buen día, no quiero ser aguafiestas, pero por que usar Hugo que funciona con archivos estaticos markdown y no ghost, que funciona igual con markdown pero sin archivos estaticos, nunca e usado drupal o un cms al estilo wordpress, tengo mi blog alojado en openshift de redhat (its free) y no me va del todo mal,igual no conozco la carga de esta comunidad.
- [Ghost](https://github.com/TryGhost/Ghost)
- [How to](https://www.howtoinstallghost.com/how-to-install-ghost-on-openshift/)
- [mi blog](http://www.ingenieroperales.com/)

**Comment by domix** [comment]
La idea de usar archivos estáticos es evitar instalar runtimes, lo único que requiere el sitio para funcionar es un webserver, no runtime. La reducción de la carga en el servidor es un efecto colateral muy bueno, el trafico ahora es poco, pero si hay más carga en el futuro, realmente no hay que hacer nada, a menos que sea demasiada la carga (cientos de miles de pageviews al día).
